---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lena-embedded
  namespace: lena
spec:
  selector:
    matchLabels:
      type: lena-embedded
      app: test
  replicas: 2
  strategy:
    type: Recreate
  minReadySeconds: 10
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        type: lena-embedded
        app: test
    spec:
      containers:
      - name: lena-embedded
        image: ghkd5216/test-1.3.4.0-lena-embedded:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8180
#        livenessProbe:
#          httpGet:
#            path: /
#            port: 8080
#          initialDelaySeconds: 30
#          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: configmap-lena-embedded
      terminationGracePeriodSeconds: 0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-lena-embedded
  namespace: lena
data:
  #JAVA_HOME: "/usr/lib/jvm/java-11-amazon-corretto"
  JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"
  LENA_JVM_HEAP_SIZE: "2048"
  LENA_JVM_METASPACE_SIZE: "256"
  LENA_MANAGER_ADDRESS: "lena-manager.lena.svc.cluster.local:7700"
  LENA_MANAGER_MONITORING_PORT: "16100"
  LENA_CONFIG_TEMPLATE_ID: "embedded-cluster"
  #LENA_SERVICE_ENDPOINT: "http://my-pay.lena.svc.cluster.local:8180"
  LENA_APP_DIR: "/usr/local/lena"
  LENA_APP_FILE: "demo.war"
  USE_OS_ROTATELOGS: "true"
  #LOG_OUTPUT_TYPE: "file"
  LOG_OUTPUT_TYPE: "console"
  #PolicySettings
  LENA_OOM_ALERT_ENABLE: "Y"
  LENA_STUCKTHREAD_ALERT_ENABLE: "Y"
  LENA_FULLGC_ALERT_ENABLE: "Y"
  LENA_EXCEPTION_ALERT_ENABLE: "Y"
  LENA_EXCEPTION_CLASS_PATTERNS: ""
  LENA_EXCEPTION_EXCLUDE_CLASS_PATTERNS: ""
  LENA_FULLSTACK_HOOKED_EXCEPTION_ENABLE: "Y"
  LENA_FULLSTACK_MAX_LINES: "3"

  #LENA_SPRING_PROFILES_ACTIVE: "dev"
  #LENA_CONFIG_SERVER_URI: "http://lena-manager.lena.svc.cluster.local:7700/lena-embed-manager/config"

---
apiVersion: v1
kind: Service
metadata:
  name: lena-embedded
  namespace: lena
spec:
  selector:
    type: lena-embedded
    app: test
  ports:
  - port: 8180
    targetPort: 8180
    nodePort: 30818
  type: NodePort
